### PR TITLE
Adapt Chrome Push API example for WebPush Variant with payload

### PR DESCRIPTION
**Pull request by idelpivnitskiy**
Now it works with WebPush Variant, supports both browsers (Chrome and Firefox) and receives encrypted push message data.

### CODE REVIEW

**Comment by Noyalcitrus** [comment]
Hai, I have tried with Push API in Mozilla Firefox and Google Chrome,
set a unified server in aerogear and set up simple push server and register the device and send the push notification to the web , I can get message version,channelId and pushendpoind but not getting the message content what I send to aerogear.
I need to know how to get the message content in browser. 
Reference : https://aerogear.org/docs/unifiedpush/aerogear-push-js/guides/#simplepush-server

**Comment by idelpivnitskiy** [comment]
Hello @Noyalcitrus,
There are a couple of notes:
1. If you are going to use a new [Push API](https://developer.mozilla.org/ru/docs/Web/API/Push_API) with the browsers, you don't need to run Simple Push Server. Simple Push is an old technology based on WebSockets and will be deprecated or removed from UPS soon.
2. We've not released a new version of UPS which supports Push API for Mozilla Firefox yet. Now it works just with Google Chrome. For more information, see https://github.com/aerogear/aerogear-js-cookbook/tree/master/chrome-webpush-unifiedpush-example. But you can compile and deploy our feature branch, which already supports Push API for Mozilla Firefox (but without payload), see https://github.com/aerogear/aerogear-unifiedpush-server/commits/webpush-variant

**Comment by subhashD** [comment]
I have used chrome-webpush. I can get the notification but in Push eventListener event I get data as null.

Any idea are appreciated.
Thank You.

**Review by subhashD — COMMENTED** [review]
After making changes rest/registry/device this api returns 400 error.

**Comment by danielpassos** [comment]
ping @matzew

**Comment by danielpassos** [comment]
This PR is open for a long time without any change. Going to close it and revisit in the future if needs. 

Thanks for your contribution.

**Pull request closed without merging**
