### PR TITLE
AGJS-165 - Angular.js / Ionic Sync Example

### PR DESCRIPTION
**Pull request by aliok**
As promised, I added the demo to cookbook. See https://issues.jboss.org/browse/AGJS-165 for more info.

### CODE REVIEW

**Comment by lfryc** [comment]
Perfect, great job @aliok . Tested locally and it works as expected.

I'm reviewing the code now... :eyes:

**Comment by lfryc** [comment]
Just one recommendation, it would be better to open two PRs for these two recipes, but let's leave it for now. :-)

**Comment by aliok** [comment]
> Just one recommendation, it would be better to open two PRs for these two recipes, but let's leave it for now. :-)

Yes, sorry about that. That was my intention actually. That is also why I created a separate issue for the canvas example. But I messed it up I think.

**Comment by lfryc** [comment]
:+1: Otherwise I like it, very nice additions!

If you would be interested, you can also write a blog for https://aerogear.org/news/ :-)

**Comment by aliok** [comment]
> If you would be interested, you can also write a blog for https://aerogear.org/news/ :-)

I will think about it. Maybe I do something more impressive and then blog about that :) Thanks for the offer.

**Comment by matzew** [comment]
+1 on the blog :-) hehe

On Tue, Apr 28, 2015 at 10:22 AM, Lukáš Fryč <notifications@github.com>
wrote:

> [image: :+1:] Otherwise I like it, very nice additions!
>
> If you would be interested, you can also write a blog for
> https://aerogear.org/news/ :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-js-cookbook/pull/11#issuecomment-96970875>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by lholmquist** [comment]
+1 awesome job.

after i merge this, i'll also add a contributor section to the main package.json

**Pull request merged**
