### PR TITLE
added list of cookbooks and project info

### PR DESCRIPTION
**Pull request by lfryc**

### CODE REVIEW

**Comment by lfryc** [comment]
I have added just cookbooks that are not deprecated. Maybe we could add also deprecated ones into separated list.

**Comment by danielpassos** [comment]
:+1:

**Comment by lholmquist** [comment]
:+1:  i wonder if we should have a separate branch where deprecated recipes go to live,  like the Land Of Misfit toys from the Rudolph Movie

**Comment by lholmquist** [comment]
:anchor:   c62ba5a0edc3771f9c46132649991d7946315259

**Comment by lfryc** [comment]
Hmm tags probably can serve that purpose, we can always deal with branching that if needed

**Pull request closed without merging**
